export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"

export const SET_PRODUCT_QTY = "SET_PRODUCT_QTY"

export const INC_PRODUCT_QTY = "INC_PRODUCT_QTY"

export const DEC_PRODUCT_QTY = "DEC_PRODUCT_QTY"

export const REMOVE_PRODUCT_IN_CART = "REMOVE_PRODUCT_IN_CART"

export const EMPTY_CART = "EMPTY_CART" 